#!/usr/bin/env node
/**
 * generate-index.mjs
 *
 * Reads the popsicle-registry git index and produces:
 *   1. public/registry-data.json   (legacy, for reference)
 *   2. src/data/registry-data.ts   (importable module — no runtime fetch)
 *
 * Usage:
 *   REGISTRY_PATH=../popsicle-registry node scripts/generate-index.mjs
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';

const REGISTRY_PATH = process.env.REGISTRY_PATH || resolve('..', 'popsicle-registry');
const SKIP = new Set(['.git', 'config.json', 'README.md', 'LICENSE', '.gitignore']);

function walkDir(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    if (SKIP.has(entry) || entry.startsWith('.')) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

function parseNdjson(filePath) {
  return readFileSync(filePath, 'utf-8')
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => JSON.parse(l));
}

console.log(`Reading registry index from: ${REGISTRY_PATH}`);

const packageFiles = walkDir(REGISTRY_PATH);
console.log(`Found ${packageFiles.length} package file(s)`);

const packages = [];
let totalSkills = 0;
let totalPipelines = 0;

for (const file of packageFiles) {
  try {
    const versions = parseNdjson(file);
    if (versions.length === 0) continue;
    const latest = versions.filter((v) => !v.yanked).at(-1) || versions.at(-1);
    const skills = latest.skills || [];
    const pipelines = latest.pipelines || [];
    totalSkills += skills.length;
    totalPipelines += pipelines.length;
    packages.push({
      name: latest.name,
      type: latest.type,
      description: latest.description || '',
      author: latest.author || '',
      repository: latest.repository || '',
      keywords: latest.keywords || [],
      latestVersion: latest.vers,
      skills,
      pipelines,
      tools: latest.tools || [],
      deps: latest.deps || [],
      versions: versions.map((v) => ({
        version: v.vers,
        source: v.source,
        yanked: v.yanked || false,
        publishedAt: v.published_at || null,
      })),
    });
  } catch (err) {
    console.warn(`Skipping ${file}: ${err.message}`);
  }
}

packages.sort((a, b) => a.name.localeCompare(b.name));

const data = {
  packages,
  stats: {
    totalPackages: packages.length,
    totalModules: packages.filter((p) => p.type === 'module').length,
    totalTools: packages.filter((p) => p.type === 'tool').length,
    totalSkills,
    totalPipelines,
  },
  generatedAt: new Date().toISOString(),
};

// Write JSON for reference
mkdirSync('public', { recursive: true });
writeFileSync(resolve('public', 'registry-data.json'), JSON.stringify(data, null, 2));

// Write importable TS module (no runtime fetch needed)
mkdirSync(resolve('src', 'data'), { recursive: true });
writeFileSync(
  resolve('src', 'data', 'registry-data.ts'),
  `// Auto-generated by scripts/generate-index.mjs — do not edit\nimport type { RegistryData } from '../app/registry';\nexport const registryData: RegistryData = ${JSON.stringify(data, null, 2)};\n`
);

console.log(`Wrote ${packages.length} packages (${totalSkills} skills, ${totalPipelines} pipelines)`);
